### ISSUE TITLE
FATAL EXCEPTION: java.lang.VerifyError

### ISSUE THREAD

**Issue by wikiti** [SempaiGames/extension-googleplaygames#26]
Hi there!

I've tried the new version of this library (using `extension-googleplayservices-basement`). After wiping out the `android` folder of my project to create a clean build, the project now compiles properly. Anyways, it's failing at runtime (startup). Here's the error shown on the test trace:

````
E/AndroidRuntime(26286): FATAL EXCEPTION: main
E/AndroidRuntime(26286): Process: org.molotovstudios.games.kob, PID: 26286
E/AndroidRuntime(26286): java.lang.VerifyError: com/google/android/gms/common/api/GoogleApiClient$Builder
E/AndroidRuntime(26286):        at com.gpgex.GameHelper.createApiClientBuilder(GameHelper.java:238)
E/AndroidRuntime(26286):        at com.gpgex.GameHelper.setup(GameHelper.java:278)
E/AndroidRuntime(26286):        at com.gpgex.GooglePlayGames$1.run(GooglePlayGames.java:66)
E/AndroidRuntime(26286):        at android.os.Handler.handleCallback(Handler.java:733)
E/AndroidRuntime(26286):        at android.os.Handler.dispatchMessage(Handler.java:95)
E/AndroidRuntime(26286):        at android.os.Looper.loop(Looper.java:136)
E/AndroidRuntime(26286):        at android.app.ActivityThread.main(ActivityThread.java:5095)
E/AndroidRuntime(26286):        at java.lang.reflect.Method.invokeNative(Native Method)
E/AndroidRuntime(26286):        at java.lang.reflect.Method.invoke(Method.java:515)
E/AndroidRuntime(26286):        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:786)
E/AndroidRuntime(26286):        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:602)
E/AndroidRuntime(26286):        at dalvik.system.NativeStart.main(Native Method)
````

The error seems to be triggered after calling `GooglePlayGames.init(false);` on main function; commenting that line disables the crash. The exception is thrown [here](https://github.com/SempaiGames/extension-googleplaygames/blob/master/dependencies/gpgex/src/com/gpgex/GameHelper.java#L238).

I'm curently running `<android target-sdk-version="21"/>`, and I've tried `19` and `23` with no luck. Not sure where to go now :confused:

P.S: Here's the full log.
[full_log.txt](https://github.com/SempaiGames/extension-googleplaygames/files/491168/full_log.txt)

**Comment by fbricker** [comment]
Hi, I've published few updates on the libraries right after releasing them (under the same version number). Just in case you have some old version, can you try uninstalling and reinstalling the extensions?
```
haxelib remove extension-googleplayservices-basement
haxelib remove extension-googleplaygames
haxelib install extension-googleplayservices-basement
haxelib install extension-googleplaygames
```

**Comment by wikiti** [comment]
After reinstalling the libraries and doing a clean build, the error still persist. Crashes in `Debug` and `Release` mode, but it only shows the backtrace in `Debug`.

I think I'll try later to build it in a clean environment (VM with windows 7 or something).

**Comment by fbricker** [comment]
Just in case... which OpenFL + Lime version are you compiling with?

**Comment by wikiti** [comment]
OpenFL 3.6.1 (with legacy mode).
Lime 2.9.1

Quite old, but I need some features that are not yet available on OpenFL4 and Lime3. Anyways, I'll give the new versions a try, and see if that's the problem.

**Comment by wikiti** [comment]
Sigh... After creating the VM, and cleanly installing the latest versions of *lime*, *openfl*.... now I've build errors (clean build, too). I think that the change from Ant to Gradle has something to do with it. Here is the backtrace:

`````
C:\Users\Dani\Downloads\King of Boxing>lime build android -debug
Incremental java compilation is an incubating feature.
:app:preBuild UP-TO-DATE
:app:preReleaseBuild UP-TO-DATE
:app:checkReleaseManifest
:app:preDebugBuild UP-TO-DATE
:deps:extension-api:preBuild UP-TO-DATE
:deps:extension-api:preReleaseBuild UP-TO-DATE
:deps:extension-api:compileReleaseNdk UP-TO-DATE
:deps:extension-api:compileLint
:deps:extension-api:copyReleaseLint UP-TO-DATE
:deps:extension-api:mergeReleaseProguardFiles UP-TO-DATE
:deps:extension-api:packageReleaseRenderscript UP-TO-DATE
:deps:extension-api:checkReleaseManifest
:deps:extension-api:prepareReleaseDependencies
:deps:extension-api:compileReleaseRenderscript UP-TO-DATE
:deps:extension-api:generateReleaseResValues UP-TO-DATE
:deps:extension-api:generateReleaseResources UP-TO-DATE
:deps:extension-api:packageReleaseResources UP-TO-DATE
:deps:extension-api:compileReleaseAidl UP-TO-DATE
:deps:extension-api:generateReleaseBuildConfig UP-TO-DATE
:deps:extension-api:mergeReleaseShaders UP-TO-DATE
:deps:extension-api:compileReleaseShaders UP-TO-DATE
:deps:extension-api:generateReleaseAssets UP-TO-DATE
:deps:extension-api:mergeReleaseAssets UP-TO-DATE
:deps:extension-api:processReleaseManifest UP-TO-DATE
:deps:extension-api:processReleaseResources UP-TO-DATE
:deps:extension-api:generateReleaseSources UP-TO-DATE
:deps:extension-api:incrementalReleaseJavaCompilationSafeguard UP-TO-DATE
:deps:extension-api:compileReleaseJavaWithJavac UP-TO-DATE
:deps:extension-api:processReleaseJavaRes UP-TO-DATE
:deps:extension-api:transformResourcesWithMergeJavaResForRelease UP-TO-DATE
:deps:extension-api:transformClassesAndResourcesWithSyncLibJarsForRelease UP-TO-DATE
:deps:extension-api:mergeReleaseJniLibFolders UP-TO-DATE
:deps:extension-api:transformNative_libsWithMergeJniLibsForRelease UP-TO-DATE
:deps:extension-api:transformNative_libsWithSyncJniLibsForRelease UP-TO-DATE
:deps:extension-api:bundleRelease UP-TO-DATE
:deps:google-play-services-base:preBuild UP-TO-DATE
:deps:google-play-services-base:preReleaseBuild UP-TO-DATE
:deps:google-play-services-base:compileReleaseNdk UP-TO-DATE
:deps:google-play-services-base:compileLint
:deps:google-play-services-base:copyReleaseLint UP-TO-DATE
:deps:google-play-services-base:mergeReleaseProguardFiles UP-TO-DATE
:deps:google-play-services-base:packageReleaseRenderscript UP-TO-DATE
:deps:google-play-services-base:checkReleaseManifest
:deps:google-play-services-base:preDebugAndroidTestBuild UP-TO-DATE
:deps:google-play-services-base:preDebugBuild UP-TO-DATE
:deps:google-play-services-base:preDebugUnitTestBuild UP-TO-DATE
:deps:google-play-services-base:preReleaseUnitTestBuild UP-TO-DATE
:deps:google-play-services-base:prepareBinDepsExtensionApiUnspecifiedLibrary UP-TO-DATE
:deps:google-play-services-base:prepareReleaseDependencies
:deps:google-play-services-base:compileReleaseRenderscript UP-TO-DATE
:deps:google-play-services-base:generateReleaseResValues UP-TO-DATE
:deps:google-play-services-base:generateReleaseResources UP-TO-DATE
:deps:google-play-services-base:packageReleaseResources UP-TO-DATE
:deps:google-play-services-base:compileReleaseAidl UP-TO-DATE
:deps:google-play-services-base:generateReleaseBuildConfig UP-TO-DATE
:deps:google-play-services-base:mergeReleaseShaders UP-TO-DATE
:deps:google-play-services-base:compileReleaseShaders UP-TO-DATE
:deps:google-play-services-base:generateReleaseAssets UP-TO-DATE
:deps:google-play-services-base:mergeReleaseAssets UP-TO-DATE
:deps:google-play-services-base:mergeReleaseResources UP-TO-DATE
:deps:google-play-services-base:processReleaseManifest UP-TO-DATE
:deps:google-play-services-base:processReleaseResources UP-TO-DATE
:deps:google-play-services-base:generateReleaseSources UP-TO-DATE
:deps:google-play-services-base:incrementalReleaseJavaCompilationSafeguard UP-TO-DATE
:deps:google-play-services-base:compileReleaseJavaWithJavac UP-TO-DATE
:deps:google-play-services-base:processReleaseJavaRes UP-TO-DATE
:deps:google-play-services-base:transformResourcesWithMergeJavaResForRelease UP-TO-DATE
:deps:google-play-services-base:transformClassesAndResourcesWithSyncLibJarsForRelease UP-TO-DATE
:deps:google-play-services-base:mergeReleaseJniLibFolders UP-TO-DATE
:deps:google-play-services-base:transformNative_libsWithMergeJniLibsForRelease UP-TO-DATE
:deps:google-play-services-base:transformNative_libsWithSyncJniLibsForRelease UP-TO-DATE
:deps:google-play-services-base:bundleRelease UP-TO-DATE
:deps:google-play-services-basement:preBuild UP-TO-DATE
:deps:google-play-services-basement:preReleaseBuild UP-TO-DATE
:deps:google-play-services-basement:compileReleaseNdk UP-TO-DATE
:deps:google-play-services-basement:compileLint
:deps:google-play-services-basement:copyReleaseLint UP-TO-DATE
:deps:google-play-services-basement:mergeReleaseProguardFiles UP-TO-DATE
:deps:google-play-services-basement:packageReleaseRenderscript UP-TO-DATE
:deps:google-play-services-basement:checkReleaseManifest
:deps:google-play-services-basement:preDebugAndroidTestBuild UP-TO-DATE
:deps:google-play-services-basement:preDebugBuild UP-TO-DATE
:deps:google-play-services-basement:preDebugUnitTestBuild UP-TO-DATE
:deps:google-play-services-basement:preReleaseUnitTestBuild UP-TO-DATE
:deps:google-play-services-basement:prepareBinDepsExtensionApiUnspecifiedLibrary UP-TO-DATE
:deps:google-play-services-basement:prepareReleaseDependencies
:deps:google-play-services-basement:compileReleaseRenderscript UP-TO-DATE
:deps:google-play-services-basement:generateReleaseResValues UP-TO-DATE
:deps:google-play-services-basement:generateReleaseResources UP-TO-DATE
:deps:google-play-services-basement:packageReleaseResources UP-TO-DATE
:deps:google-play-services-basement:compileReleaseAidl UP-TO-DATE
:deps:google-play-services-basement:generateReleaseBuildConfig UP-TO-DATE
:deps:google-play-services-basement:mergeReleaseShaders UP-TO-DATE
:deps:google-play-services-basement:compileReleaseShaders UP-TO-DATE
:deps:google-play-services-basement:generateReleaseAssets UP-TO-DATE
:deps:google-play-services-basement:mergeReleaseAssets UP-TO-DATE
:deps:google-play-services-basement:mergeReleaseResources UP-TO-DATE
:deps:google-play-services-basement:processReleaseManifest UP-TO-DATE
:deps:google-play-services-basement:processReleaseResources UP-TO-DATE
:deps:google-play-services-basement:generateReleaseSources UP-TO-DATE
:deps:google-play-services-basement:incrementalReleaseJavaCompilationSafeguard UP-TO-DATE
:deps:google-play-services-basement:compileReleaseJavaWithJavac UP-TO-DATE
:deps:google-play-services-basement:processReleaseJavaRes UP-TO-DATE
:deps:google-play-services-basement:transformResourcesWithMergeJavaResForRelease UP-TO-DATE
:deps:google-play-services-basement:transformClassesAndResourcesWithSyncLibJarsForRelease UP-TO-DATE
:deps:google-play-services-basement:mergeReleaseJniLibFolders UP-TO-DATE
:deps:google-play-services-basement:transformNative_libsWithMergeJniLibsForRelease UP-TO-DATE
:deps:google-play-services-basement:transformNative_libsWithSyncJniLibsForRelease UP-TO-DATE
:deps:google-play-services-basement:bundleRelease UP-TO-DATE
:deps:google-play-services-drive:preBuild UP-TO-DATE
:deps:google-play-services-drive:preReleaseBuild UP-TO-DATE
:deps:google-play-services-drive:compileReleaseNdk UP-TO-DATE
:deps:google-play-services-drive:compileLint
:deps:google-play-services-drive:copyReleaseLint UP-TO-DATE
:deps:google-play-services-drive:mergeReleaseProguardFiles UP-TO-DATE
:deps:google-play-services-drive:packageReleaseRenderscript UP-TO-DATE
:deps:google-play-services-drive:checkReleaseManifest
:deps:google-play-services-drive:preDebugAndroidTestBuild UP-TO-DATE
:deps:google-play-services-drive:preDebugBuild UP-TO-DATE
:deps:google-play-services-drive:preDebugUnitTestBuild UP-TO-DATE
:deps:google-play-services-drive:preReleaseUnitTestBuild UP-TO-DATE
:deps:google-play-services-drive:prepareBinDepsExtensionApiUnspecifiedLibrary UP-TO-DATE
:deps:google-play-services-drive:prepareReleaseDependencies
:deps:google-play-services-drive:compileReleaseRenderscript UP-TO-DATE
:deps:google-play-services-drive:generateReleaseResValues UP-TO-DATE
:deps:google-play-services-drive:generateReleaseResources UP-TO-DATE
:deps:google-play-services-drive:packageReleaseResources UP-TO-DATE
:deps:google-play-services-drive:compileReleaseAidl UP-TO-DATE
:deps:google-play-services-drive:generateReleaseBuildConfig UP-TO-DATE
:deps:google-play-services-drive:mergeReleaseShaders UP-TO-DATE
:deps:google-play-services-drive:compileReleaseShaders UP-TO-DATE
:deps:google-play-services-drive:generateReleaseAssets UP-TO-DATE
:deps:google-play-services-drive:mergeReleaseAssets UP-TO-DATE
:deps:google-play-services-drive:mergeReleaseResources UP-TO-DATE
:deps:google-play-services-drive:processReleaseManifest UP-TO-DATE
:deps:google-play-services-drive:processReleaseResources UP-TO-DATE
:deps:google-play-services-drive:generateReleaseSources UP-TO-DATE
:deps:google-play-services-drive:incrementalReleaseJavaCompilationSafeguard UP-TO-DATE
:deps:google-play-services-drive:compileReleaseJavaWithJavac UP-TO-DATE
:deps:google-play-services-drive:processReleaseJavaRes UP-TO-DATE
:deps:google-play-services-drive:transformResourcesWithMergeJavaResForRelease UP-TO-DATE
:deps:google-play-services-drive:transformClassesAndResourcesWithSyncLibJarsForRelease UP-TO-DATE
:deps:google-play-services-drive:mergeReleaseJniLibFolders UP-TO-DATE
:deps:google-play-services-drive:transformNative_libsWithMergeJniLibsForRelease UP-TO-DATE
:deps:google-play-services-drive:transformNative_libsWithSyncJniLibsForRelease UP-TO-DATE
:deps:google-play-services-drive:bundleRelease UP-TO-DATE
:deps:google-play-services-games:preBuild UP-TO-DATE
:deps:google-play-services-games:preReleaseBuild UP-TO-DATE
:deps:google-play-services-games:compileReleaseNdk UP-TO-DATE
:deps:google-play-services-games:compileLint
:deps:google-play-services-games:copyReleaseLint UP-TO-DATE
:deps:google-play-services-games:mergeReleaseProguardFiles UP-TO-DATE
:deps:google-play-services-games:packageReleaseRenderscript UP-TO-DATE
:deps:google-play-services-games:checkReleaseManifest
:deps:google-play-services-games:preDebugAndroidTestBuild UP-TO-DATE
:deps:google-play-services-games:preDebugBuild UP-TO-DATE
:deps:google-play-services-games:preDebugUnitTestBuild UP-TO-DATE
:deps:google-play-services-games:preReleaseUnitTestBuild UP-TO-DATE
:deps:google-play-services-games:prepareBinDepsExtensionApiUnspecifiedLibrary UP-TO-DATE
:deps:google-play-services-games:prepareReleaseDependencies
:deps:google-play-services-games:compileReleaseRenderscript UP-TO-DATE
:deps:google-play-services-games:generateReleaseResValues UP-TO-DATE
:deps:google-play-services-games:generateReleaseResources UP-TO-DATE
:deps:google-play-services-games:packageReleaseResources UP-TO-DATE
:deps:google-play-services-games:compileReleaseAidl UP-TO-DATE
:deps:google-play-services-games:generateReleaseBuildConfig UP-TO-DATE
:deps:google-play-services-games:mergeReleaseShaders UP-TO-DATE
:deps:google-play-services-games:compileReleaseShaders UP-TO-DATE
:deps:google-play-services-games:generateReleaseAssets UP-TO-DATE
:deps:google-play-services-games:mergeReleaseAssets UP-TO-DATE
:deps:google-play-services-games:mergeReleaseResources UP-TO-DATE
:deps:google-play-services-games:processReleaseManifest UP-TO-DATE
:deps:google-play-services-games:processReleaseResources UP-TO-DATE
:deps:google-play-services-games:generateReleaseSources UP-TO-DATE
:deps:google-play-services-games:incrementalReleaseJavaCompilationSafeguard UP-TO-DATE
:deps:google-play-services-games:compileReleaseJavaWithJavac UP-TO-DATE
:deps:google-play-services-games:processReleaseJavaRes UP-TO-DATE
:deps:google-play-services-games:transformResourcesWithMergeJavaResForRelease UP-TO-DATE
:deps:google-play-services-games:transformClassesAndResourcesWithSyncLibJarsForRelease UP-TO-DATE
:deps:google-play-services-games:mergeReleaseJniLibFolders UP-TO-DATE
:deps:google-play-services-games:transformNative_libsWithMergeJniLibsForRelease UP-TO-DATE
:deps:google-play-services-games:transformNative_libsWithSyncJniLibsForRelease UP-TO-DATE
:deps:google-play-services-games:bundleRelease UP-TO-DATE
:deps:google-play-services-plus:preBuild UP-TO-DATE
:deps:google-play-services-plus:preReleaseBuild UP-TO-DATE
:deps:google-play-services-plus:compileReleaseNdk UP-TO-DATE
:deps:google-play-services-plus:compileLint
:deps:google-play-services-plus:copyReleaseLint UP-TO-DATE
:deps:google-play-services-plus:mergeReleaseProguardFiles UP-TO-DATE
:deps:google-play-services-plus:packageReleaseRenderscript UP-TO-DATE
:deps:google-play-services-plus:checkReleaseManifest
:deps:google-play-services-plus:preDebugAndroidTestBuild UP-TO-DATE
:deps:google-play-services-plus:preDebugBuild UP-TO-DATE
:deps:google-play-services-plus:preDebugUnitTestBuild UP-TO-DATE
:deps:google-play-services-plus:preReleaseUnitTestBuild UP-TO-DATE
:deps:google-play-services-plus:prepareBinDepsExtensionApiUnspecifiedLibrary UP-TO-DATE
:deps:google-play-services-plus:prepareReleaseDependencies
:deps:google-play-services-plus:compileReleaseRenderscript UP-TO-DATE
:deps:google-play-services-plus:generateReleaseResValues UP-TO-DATE
:deps:google-play-services-plus:generateReleaseResources UP-TO-DATE
:deps:google-play-services-plus:packageReleaseResources UP-TO-DATE
:deps:google-play-services-plus:compileReleaseAidl UP-TO-DATE
:deps:google-play-services-plus:generateReleaseBuildConfig UP-TO-DATE
:deps:google-play-services-plus:mergeReleaseShaders UP-TO-DATE
:deps:google-play-services-plus:compileReleaseShaders UP-TO-DATE
:deps:google-play-services-plus:generateReleaseAssets UP-TO-DATE
:deps:google-play-services-plus:mergeReleaseAssets UP-TO-DATE
:deps:google-play-services-plus:mergeReleaseResources UP-TO-DATE
:deps:google-play-services-plus:processReleaseManifest UP-TO-DATE
:deps:google-play-services-plus:processReleaseResources UP-TO-DATE
:deps:google-play-services-plus:generateReleaseSources UP-TO-DATE
:deps:google-play-services-plus:incrementalReleaseJavaCompilationSafeguard UP-TO-DATE
:deps:google-play-services-plus:compileReleaseJavaWithJavac UP-TO-DATE
:deps:google-play-services-plus:processReleaseJavaRes UP-TO-DATE
:deps:google-play-services-plus:transformResourcesWithMergeJavaResForRelease UP-TO-DATE
:deps:google-play-services-plus:transformClassesAndResourcesWithSyncLibJarsForRelease UP-TO-DATE
:deps:google-play-services-plus:mergeReleaseJniLibFolders UP-TO-DATE
:deps:google-play-services-plus:transformNative_libsWithMergeJniLibsForRelease UP-TO-DATE
:deps:google-play-services-plus:transformNative_libsWithSyncJniLibsForRelease UP-TO-DATE
:deps:google-play-services-plus:bundleRelease UP-TO-DATE
:deps:gpgex:preBuild UP-TO-DATE
:deps:gpgex:preReleaseBuild UP-TO-DATE
:deps:gpgex:compileReleaseNdk UP-TO-DATE
:deps:gpgex:compileLint
:deps:gpgex:copyReleaseLint UP-TO-DATE
:deps:gpgex:mergeReleaseProguardFiles UP-TO-DATE
:deps:gpgex:packageReleaseRenderscript UP-TO-DATE
:deps:gpgex:checkReleaseManifest
:deps:gpgex:preDebugAndroidTestBuild UP-TO-DATE
:deps:gpgex:preDebugBuild UP-TO-DATE
:deps:gpgex:preDebugUnitTestBuild UP-TO-DATE
:deps:gpgex:preReleaseUnitTestBuild UP-TO-DATE
:deps:gpgex:prepareBinDepsExtensionApiUnspecifiedLibrary UP-TO-DATE
:deps:gpgex:prepareReleaseDependencies
:deps:gpgex:compileReleaseRenderscript UP-TO-DATE
:deps:gpgex:generateReleaseResValues UP-TO-DATE
:deps:gpgex:generateReleaseResources UP-TO-DATE
:deps:gpgex:packageReleaseResources UP-TO-DATE
:deps:gpgex:compileReleaseAidl UP-TO-DATE
:deps:gpgex:generateReleaseBuildConfig UP-TO-DATE
:deps:gpgex:mergeReleaseShaders UP-TO-DATE
:deps:gpgex:compileReleaseShaders UP-TO-DATE
:deps:gpgex:generateReleaseAssets UP-TO-DATE
:deps:gpgex:mergeReleaseAssets UP-TO-DATE
:deps:gpgex:mergeReleaseResources UP-TO-DATE
:deps:gpgex:processReleaseManifest UP-TO-DATE
:deps:gpgex:processReleaseResources
C:\Users\Dani\Downloads\King of Boxing\bin\android\debug\bin\deps\gpgex\build\intermediates\bundles\release\aapt\AndroidManifest.xml:11:28-65: AAPT: No resource found that matches the given name (at 'value' with value '@integer/google_play_services_version').

:deps:gpgex:processReleaseResources FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':deps:gpgex:processReleaseResources'.
> com.android.ide.common.process.ProcessException: org.gradle.process.internal.ExecException: Process 'command 'C:\Dev\Android\SDK\build-tools\24.0.1\aapt.exe finished with non-zero exit value 1

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.

BUILD FAILED
``````

Am I doing something wrong?

**Comment by wikiti** [comment]
After removing `extension-iap` and `extension-admob` from the project, the build error still exists.

I've created a file called `version.xml` in the `<project root>\bin\android\debug\bin\deps\gpgex\res\version.xml` with the following content:

````xml
<?xml version="1.0" encoding="utf-8" ?> 
<resources xmlns:ns1="urn:oasis:names:tc:xliff:document:1.2">
  <integer name="google_play_services_version">9683000</integer> 
</resources>
````

Now, the compiler passes the configuration section, but fails with loads of errors referencing java classes that don't exist, related to package `com.google.android.gms`.

[build.log.txt](https://github.com/SempaiGames/extension-googleplaygames/files/503824/build.log.txt)

**Comment by wikiti** [comment]
The build error seems to be fixed on https://github.com/SempaiGames/extension-googleplaygames/pull/28

**Comment by mgalpy** [comment]
I know this has been closed, but I can't seem to get past this error still. Compiling in windows and here is what I have installed (using android 23): 
haxelib list
bezier: [1.0.4]
extension-android-support-v4: [1.0.0]
extension-googleplaygames: [1.5.2]
extension-googleplayservices-basement: [1.1.0]
flixel-addons: [2.1.0]
flixel-demos: [2.2.0]
flixel-templates: [2.0.2]
flixel-tools: [1.1.3]
flixel-ui: [2.1.0]
flixel: [4.1.1] git
format: [3.2.1]
hscript: [2.0.7]
hxcpp-debugger: 1.0.6 [git]
hxcpp: [3.3.49]
lime: [2.9.1]
mloader: [2.2.1]
msignal: [1.2.4]
nape: [2.0.20]
openfl: [3.6.1]
xmlTools: [1.4.0]

**Comment by wikiti** [comment]
@mgalpy Could you try compiling your project on a clean environment (for example, a virtual machine) with OpenFL4? As far as I know, this extension now uses Gradle (used in OpenFL 4) instead of Ant (used in OpenFL 3)

**Comment by mgalpy** [comment]
@wikiti Thanks for the quick reply, I noticed that there was a merged pull request to "Add Gradle support while keeping Ant support" : https://github.com/SempaiGames/extension-googleplaygames/pull/28 and was hoping that the latest version could still be used with openfl 3.6.1 because I need to use the library flixel and it's only compatible with openfl 3.6.1 at the moment.

**Comment by fbricker** [comment]
Hi, the current version is still working with OpenFL 3.6.1
Have you set the Google play games ID and the Android SDK Target version on your project.xml?
```xml
<setenv name="GOOGLE_PLAY_GAMES_ID" value="32180581421" /> <!-- REPLACE THIS WITH YOUR GOOGLE PLAY GAMES ID! -->
<android target-sdk-version="23" if="android" />
```

If you already made that, please create some small project that can reproduce your issue and share it on github, so we can test it over here.

**Comment by mgalpy** [comment]
Hello, ok great. Yes I did add the Google play games ID and the Android SDK Target inside project.xml. I will create the small project to share on github and I'll update with a link tonight, Thank you.

**Comment by mgalpy** [comment]
Hi, I created a small test project, and checked it into my github account here: https://github.com/mgalpy/OpenFLSempaiGamesGoogleServiceTest

I also created a travis-ci file / build so that you can see a Linux recreation of my environment and to hopefully make it easier to test : https://travis-ci.org/mgalpy/OpenFLSempaiGamesGoogleServiceTest/builds/176024253

The generated apk file can be downloaded here :  http://arcademechanics.com/download/pubgame/OpenFLHelloWorld-debug.apk

I replaced my my actual google play game id value in the project file with a placeholder (I hope that is OK I wasn't sure if it was something that I should check in publicly).

For the travis build I am installing android-sdk_r24.4.1-linux.tgz and using :
android-23
tools
platform-tools 
build-tools-19.1.0
sys-img-armeabi-v7a-google_apis-23
sys-img-x86_64-google_apis-23
addon-google_apis-google-23
extra-android-m2repository
extra-google-m2repository
extra-google-google_play_services

**Comment by fbricker** [comment]
Hi, I've tested your test-project and found out extension-android-support-v4 was missing.
Once I added that, the project stopped crashing.

So, you can either add extension-android-support-v4 to your project.xml, or update the extension-googleplaygames from haxelib (as I've added the dependency there and uploaded a new version to haxelib already).

Thanks for reporting!

**Comment by mgalpy** [comment]
After updating to use your latest version and also adding the obsolete Android Support Library everything worked. Thank you, much appreciated!

**Comment by Txori** [comment]
Hi @fbricker, I'm trying to run your lib for days now... So I tried to compile @mgalpy strip down example, without luck.

Here's my system setup:

actuate: [1.8.7]
box2d: [1.2.3]
extension-android-support-v4: [1.0.0]
extension-googleplaygames: [1.5.7]
extension-googleplayservices-basement: [1.1.0]
extension-share: [2.4.3]
flixel-addons: git [dev:/usr/lib/haxe/lib/flixel-addons/git]
flixel-ui: git [dev:/usr/lib/haxe/lib/flixel-ui/git]
flixel: git 4.2.1 [dev:/usr/lib/haxe/lib/flixel/git]
format: [3.3.0]
hxcpp: [3.4.64]
layout: [1.2.1]
lime-tools: [1.5.7]
lime: [2.9.1]
nape: [2.0.20]
openfl-unityads: [1.0.7]
openfl: [3.6.1]
svg: [1.1.1]
swf: [2.3.1]
systools: [1.1.0]

I've tried with several Android versions (21, 23, 25) and Android Support Repository 47.

And here's the error I'm getting:

E/AndroidRuntime( 1127): FATAL EXCEPTION: main
E/AndroidRuntime( 1127): Process: com.MyExample.OpenFLHelloWorld, PID: 1127
E/AndroidRuntime( 1127): java.lang.NoClassDefFoundError: Failed resolution of: Landroid/support/v4/util/ArrayMap;
E/AndroidRuntime( 1127): 	at com.google.android.gms.common.api.GoogleApiClient$Builder.<init>(Unknown Source)
E/AndroidRuntime( 1127): 	at com.google.android.gms.common.api.GoogleApiClient$Builder.<init>(Unknown Source)
E/AndroidRuntime( 1127): 	at com.gpgex.GameHelper.createApiClientBuilder(GameHelper.java:238)
E/AndroidRuntime( 1127): 	at com.gpgex.GameHelper.setup(GameHelper.java:278)
E/AndroidRuntime( 1127): 	at com.gpgex.GooglePlayGames$1.run(GooglePlayGames.java:66)
E/AndroidRuntime( 1127): 	at android.os.Handler.handleCallback(Handler.java:739)
E/AndroidRuntime( 1127): 	at android.os.Handler.dispatchMessage(Handler.java:95)
E/AndroidRuntime( 1127): 	at android.os.Looper.loop(Looper.java:211)
E/AndroidRuntime( 1127): 	at android.app.ActivityThread.main(ActivityThread.java:5389)
E/AndroidRuntime( 1127): 	at java.lang.reflect.Method.invoke(Native Method)
E/AndroidRuntime( 1127): 	at java.lang.reflect.Method.invoke(Method.java:372)
E/AndroidRuntime( 1127): 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1020)
E/AndroidRuntime( 1127): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:815)
E/AndroidRuntime( 1127): Caused by: java.lang.ClassNotFoundException: Didn't find class "android.support.v4.util.ArrayMap" on path: DexPathList[[zip file "/data/app/com.MyExample.OpenFLHelloWorld-2/base.apk"],nativeLibraryDirectories=[/data/app/com.MyExample.OpenFLHelloWorld-2/lib/arm, /vendor/lib, /system/lib]]

What can I do in order to resolve this?
Thanks for your help.
